"""initial migration

Revision ID: 19f226cd7bdc
Revises: fe20bc96ac52
Create Date: 2017-02-15 12:40:43.472000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19f226cd7bdc'
down_revision = 'fe20bc96ac52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('new_email', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_users_new_email'), 'users', ['new_email'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_new_email'), table_name='users')
    op.drop_column('users', 'new_email')
    # ### end Alembic commands ###
